variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_TLS_CERTDIR: ''

default:
  image: docker:24.0.9
  services:
    - name: docker:24.0.9-dind
  before_script:
    - apk add bash curl
    - curl --silent
      "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer"
      | bash
    - mv .secure_files/.env .env.local
    - docker info
    - docker login -u $SCCS_REGISTRY_USER -p $SCCS_REGISTRY_TOKEN $SCCS_REGISTRY

build:
  stage: build
  script:
    - docker compose -f docker-compose.yml build wsrn-website
    - docker push $SCCS_REGISTRY/sccs/wsrn-website/wsrn-website:latest

deploy_docker_stage:
  stage: deploy
  variables:
    DOCKER_HOST: 'tcp://130.58.218.21:2376'
  script:
    - docker stack deploy --with-registry-auth -c ./docker-compose.yml wsrn-website
