services:
  liquidsoap:
    image: wsrn_liquidsoap:latest
    restart: unless-stopped
    container_name: wsrn-playback-docker
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik'
        - 'traefik.port=80'
        - 'traefik.http.routers.wsrn_liquidsoap.entrypoints=https'
        - 'traefik.http.routers.crumb.rule=Host(`liquidsoap.wsrn.sccs.swarthmore.edu`)'
        - 'traefik.http.routers.wsrn_liquidsoap.tls=true'
        - 'traefik.http.routers.wsrn_liquidsoap.tls.certresolver=letsEncrypt'
    command: ./myscript.liq
    volumes:
      - wsrn-archive:/app/data
      - wsrn-playlist:/app/playlist.m3u
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  wsrn-archive:
    name: wsrn-archive
    driver_opts:
      type: nfs
      o: 'nfsvers=4,addr=130.58.218.26,rw,nolock,soft'
      device: ':/volumes/dcrepublic/wsrn/archive'

  wsrn-playlist:
    name: wsrn-archive
    driver_opts:
      type: nfs
      o: 'nfsvers=4,addr=130.58.218.26,rw,nolock,soft'
      device: ':/volumes/dcrepublic/wsrn/archive/playlist.m3u'
