# Force push code to GitLab for deployment

name: Mirror

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: action-pack/gitlab-sync@v3
        with:
          # GitLab repo URL
          url: https://gitlab.sccs.swarthmore.edu/sccs/wsrn-website.git
          # GitLab username
          username: mirrorbot
          # GitLab token
          token: ${{ secrets.GITLAB_TOKEN }}
